homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 45.9553
  longitude: -122.7622
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 300
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   # Uncomment next line if you want to enable legacy API password support
   # - type: legacy_api_password


# Enable the auth component
auth:

#cloud:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  # trusted_networks: 192.168.42.0/24
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

recorder:
  #  db_url: mysql://homeassistant:homeassistdb@192.168.42.2/homeassistant
  purge_keep_days: 8
  purge_interval: 1
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.date
      - device_tracker.lee_nexus5
      - device_tracker.lee_nexus5_ping
      - sensor.deck_westside_cam_filename
      - device_tracker.nexus_5
  # Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Weather prediction
#sensor:
#  - platform: yr

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

mqtt:
  broker: 192.168.42.5


#group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
mysensors: !include components/mysensors.yaml
light: !include_dir_merge_list lights/
switch: !include_dir_merge_list switches/
sensor: !include_dir_merge_list sensors/
notify: !include components/notify.yaml
device_tracker: !include components/tracker.yaml
google_assistant: !include components/google_assistant.yaml
media_player: !include components/media.yaml

binary_sensor:
  - platform: mqtt
    name: "Deck Westside Cam Control"
    state_topic: "home/westdeck/light/power"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 2

input_datetime:
  coffee_start:
    name: Coffee Start Time
    has_time: true
    has_date: false

input_boolean:
  coffee_timer_enable:
    name: Enable Coffee Timer

zone:
    - name: Home
      latitude: 45.9553
      longitude: -122.7622
      radius: 500
      icon: mdi:home

history_graph:
  gr1:
    name: Temperatures
    entities:
      - sensor.tempsensorrfm95_202_2
      - sensor.shoprfm95_201_2
      - sensor.outside_under_deck_temp
      - sensor.inside_basement_temp
    #  - sensor.inside_temperature
    hours_to_show: 72
    # refresh: 0

logger:
#  default: warn
  default: debug
  logs:
#    homeassistant.components.mysensors: debug
#    mysensors: debug
    homeassistant.components.mysensors: warn
    mysensors: warn
#    homeassistant.components.http.view: debug
    homeassistant.components.google_assistant: debug

#camera:
#  - platform: local_file
#    name: "Westside Deck Camera"
#    filepath: /media/cams/source/deck/tmp.jpg
#    #filepath: "/media/cams/source/deck/source/{{ ('sensor.deck_westside_cam_filename') }}"
