- alias: Coffee Button On
  trigger: 
    platform: state
    entity_id: switch.coffee_espresso_10_0
    to: 'on'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.coffee_espresso_10_0
- alias: Coffee Button Off
  trigger: 
    platform: state
    entity_id: switch.coffee_espresso_10_0
    to: 'off'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.coffee_espresso_10_0
- alias: Coffee Maker 3hr
  trigger:
    platform: state
    entity_id: switch.coffee_espresso_10_0
    to: 'on'
    for:
      hours: 3
  action:
    service: switch.turn_off
    entity_id: switch.coffee_espresso_10_0
- alias: Coffee Timer
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.coffee_timer_enable
        state: 'on'
      - condition: template
        value_template: '{{ now().hour == (states.input_datetime.coffee_start.attributes.hour  | round(0)) and  now().minute == (states.input_datetime.coffee_start.attributes.minute  | round(0) )  }}'
  action:
    service: switch.turn_on
    entity_id: switch.coffee_espresso_10_0

