- alias: Deck Westside Cam Control ON
  trigger:
    platform: state
    entity_id: binary_sensor.deck_westside_cam_control
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.yeelight_mono1_34ce0088229a
- alias: Deck West Side Light 30min
  trigger:
    platform: state
    entity_id: light.yeelight_mono1_34ce0088229a
    to: 'on'
    for:
      minutes: 30
  action:
  - service: light.turn_off
    entity_id: light.yeelight_mono1_34ce0088229a
- alias: Basement Door Light 30min
  trigger:
    platform: state
    entity_id: switch.relay_button_1_1
    to: 'on'
    for:
      minutes: 30
  action:
  - service: switch.turn_off
    entity_id: switch.relay_button_1_1

- alias: Outside Lights on when arriving home
  trigger:
    platform: state
#    entity_id: device_tracker.lee_galaxys8, device_tracker.lee_galaxys8_ping
    entity_id: group.presence
    from: not_home
    to: home
  condition:
    condition: sun
    after: sunset
  action:
  - service: light.turn_on
    entity_id: light.yeelight_mono1_34ce0088229a
  - service: switch.turn_on
    entity_id: switch.relay_button_1_1
