- alias: Bedroom PIR On
  trigger: 
    platform: state
    entity_id: binary_sensor.ir_rxtx_12_5
    to: 'on'
  condition:
    condition: state
    entity_id:  group.bedroomlights
    state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.bedroom_front_light
        - light.bedroom_rear_light

- alias: Basement PIR On
  trigger: 
    platform: state
    entity_id: binary_sensor.ir_rxtx_13_5
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.basement_fluorescent

- alias: Basement PIR Timer
  trigger:
    platform: state
    entity_id: binary_sensor.ir_rxtx_13_5
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: light.basement_fluorescent
    state: 'on'
  action:
    service: light.turn_off
    data:
      entity_id: light.basement_fluorescent
